### ISSUE TITLE
Create get all funtion 

### ISSUE THREAD

**Issue by rafatorrealba** [rafatorrealba/ubiot-network#3]
Se debe crear la funcion get all

**Comment by ubiot-alejandro** [comment]
Function added, code updated.
Test branch deleted.

Commits:
- 5f1c7c0dbe30245e6adb760fb57c69afb262a9e8
- 7013d8f076c78a3b34f812f06ec96c8e7bebfd82
- b3b4b26dd0aabdcd0bfdf49540abec401a1f1b8d
- b74c618cf7136ca934090ab48b9d666d2ab6f164
- 3f90270016db7df1f631e534e203ed307385ffc8
